export const lorem10 =
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt, ipsum.';
export const lorem20 =
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Similique, quam pariatur nostrum adipisci praesentium expedita aliquam. Itaque officia repellat omnis?';

export const lorem50 =
  'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima totam vero similique obcaecati laudantium, autem, tenetur delectus possimus qui odit, beatae est placeat sapiente quo dolor quae nostrum id maxime repellendus repudiandae. Dolores autem pariatur doloribus vero nostrum reprehenderit ex perspiciatis ut voluptatum atque delectus esse, inventore facere eum eius.';

export const lorem200 =
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas quaerat sapiente ipsum quidem tenetur, harum aliquam sit! Perspiciatis sint quis, sed eveniet quam blanditiis ut tempore aut suscipit? Vel, excepturi adipisci. Aut sunt ea earum nobis dolor nostrum itaque non delectus inventore aliquam harum placeat vitae esse laboriosam impedit dignissimos iusto provident aspernatur perspiciatis beatae, enim eius libero officiis cupiditate. Necessitatibus molestiae pariatur aspernatur minus perferendis animi explicabo rem consequuntur voluptatibus maiores maxime, modi, cumque a saepe fugit ipsum dolorum beatae cum, quasi repellendus doloribus culpa repudiandae nam ipsa? Neque sint perspiciatis illum earum error corrupti. Enim natus, porro rem modi amet eos harum itaque quia officia dolorem quis voluptatem expedita necessitatibus a nesciunt unde cumque ut. Adipisci temporibus quaerat sunt praesentium doloribus deserunt, itaque omnis aliquid voluptatum nam, dolor in officiis consequatur quae laboriosam quo tempora. Delectus magnam illo exercitationem, veritatis nihil tenetur totam? Animi a quas laborum quaerat aspernatur eius qui placeat officia nesciunt ipsum officiis cupiditate minus consectetur impedit, obcaecati accusamus illum at atque quidem quae quis labore rem modi distinctio. Accusamus delectus vero neque id sapiente nulla recusandae impedit explicabo doloribus ad. Possimus quia ducimus in, a ex dolore explicabo illum vel, quisquam officia pariatur voluptatem.';
